version: "3"
services:
  icarus:
    image: mornedhels/icarus-server:latest
    container_name: icarus-server
    hostname: icarus
    restart: unless-stopped
    stop_grace_period: 120s
    ports:
      - "17777:17777/udp"
      - "27015:27015/udp"
    volumes:
      - ./data:/home/icarus/drive_c/icarus
      - ./game:/opt/icarus
    environment:
      - SERVER_NAME=CostaDelMars
      - SERVER_PASSWORD=costa3
      - SERVER_ADMIN_PASSWORD=A8jmFs356smA
      - SERVER_PORT=17777
      - SERVER_QUERYPORT=27015
      - SERVER_RESUME_PROSPECT=False
      - PUID=4711
      - PGID=4711
